In [3]:
import pandas as pd
pd.__version__

'2.3.3'

In [4]:
s = pd.Series([10,20,30], name ="points")
df = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [19,21,20],
    "gpa": [3.2, 3.8, 3.5]
})
print(s)
print(df)

0    10
1    20
2    30
Name: points, dtype: int64
  name  age  gpa
0    A   19  3.2
1    B   21  3.8
2    C   20  3.5

In [5]:
df.head()

  name  age  gpa
0    A   19  3.2
1    B   21  3.8
2    C   20  3.5

In [6]:
df.tail(2)

  name  age  gpa
1    B   21  3.8
2    C   20  3.5

In [7]:
df.shape

(3, 3)

In [8]:
df.columns

Index(['name', 'age', 'gpa'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   gpa     3 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes

In [10]:
df["age"]

0    19
1    21
2    20
Name: age, dtype: int64

In [11]:
df[["age","gpa"]]

   age  gpa
0   19  3.2
1   21  3.8
2   20  3.5

In [12]:
df.loc[0]

name      A
age      19
gpa     3.2
Name: 0, dtype: object

In [13]:
df.loc[0,"age"]

np.int64(19)

In [14]:
df.iloc[0]

name      A
age      19
gpa     3.2
Name: 0, dtype: object

In [15]:
df.iloc[0,1]

np.int64(19)

In [16]:
df.iloc[0:2, 1:3]

   age  gpa
0   19  3.2
1   21  3.8

In [17]:
df[(df["gpa"] >= 3.5) & (df["age"] >= 20)]

  name  age  gpa
1    B   21  3.8
2    C   20  3.5

In [18]:
df = pd.DataFrame({
    "expense": [100, 50, 120, 200, 250, 20],
    "category": ["food", "food", "transport", "rent", "rent", "snack"],
    "day": ["Mon", "Mon", "Tue", "Wed", "Wed", "Thu"]
})

In [19]:
df.head(3)

   expense   category  day
0      100       food  Mon
1       50       food  Mon
2      120  transport  Tue

In [20]:
print(df.shape)

(6, 3)

In [21]:
df["expense"]

0    100
1     50
2    120
3    200
4    250
5     20
Name: expense, dtype: int64

In [22]:
df[["expense", "category"]]

   expense   category
0      100       food
1       50       food
2      120  transport
3      200       rent
4      250       rent
5       20      snack

In [23]:
df[df["expense"] >= 120]

   expense   category  day
2      120  transport  Tue
3      200       rent  Wed
4      250       rent  Wed

In [24]:
df[df["category"] == "rent"]

   expense category  day
3      200     rent  Wed
4      250     rent  Wed

In [25]:
from io import StringIO

csv_data = StringIO("""
age,income,city,spend
25,50000,NY,200
30,60000,LA,NaN
22,,NY,120
35,80000,Chicago,300
28,55000,,150
""")

In [26]:
df = pd.read_csv(csv_data)

In [27]:
print(df)

   age   income     city  spend
0   25  50000.0       NY  200.0
1   30  60000.0       LA    NaN
2   22      NaN       NY  120.0
3   35  80000.0  Chicago  300.0
4   28  55000.0      NaN  150.0

In [28]:
df.isna().sum()

age       0
income    1
city      1
spend     1
dtype: int64

In [29]:
df_drop = df.dropna()
df_drop

   age   income     city  spend
0   25  50000.0       NY  200.0
3   35  80000.0  Chicago  300.0

In [30]:
df.dropna(subset = ["income"])

   age   income     city  spend
0   25  50000.0       NY  200.0
1   30  60000.0       LA    NaN
3   35  80000.0  Chicago  300.0
4   28  55000.0      NaN  150.0

In [31]:
df["income"] = df["income"].fillna(df["income"].mean())
df["spend"] = df["spend"].fillna(df["spend"].mean())

In [32]:
df

   age   income     city  spend
0   25  50000.0       NY  200.0
1   30  60000.0       LA  192.5
2   22  61250.0       NY  120.0
3   35  80000.0  Chicago  300.0
4   28  55000.0      NaN  150.0

In [33]:
df["city"] = df["city"].fillna(df["city"].mode()[0])

In [34]:
df

   age   income     city  spend
0   25  50000.0       NY  200.0
1   30  60000.0       LA  192.5
2   22  61250.0       NY  120.0
3   35  80000.0  Chicago  300.0
4   28  55000.0       NY  150.0

In [35]:
df.dtypes

age         int64
income    float64
city       object
spend     float64
dtype: object

In [36]:
df.isna().sum()

age       0
income    0
city      0
spend     0
dtype: int64

In [37]:
df = pd.DataFrame({
    "age": [20, 22, None, 30, 28],
    "salary": [30000, None, 45000, 60000, None],
    "department": ["IT", "HR", "IT", None, "HR"]
})
df

    age   salary department
0  20.0  30000.0         IT
1  22.0      NaN         HR
2   NaN  45000.0         IT
3  30.0  60000.0       None
4  28.0      NaN         HR

In [38]:
df.isna().sum()

age           1
salary        2
department    1
dtype: int64

In [39]:
df["age"] = df["age"].fillna(df["age"].mean())

In [40]:
df["salary"] = df["salary"].fillna(df["salary"].median())

In [41]:
df["department"] = df["department"].fillna(df["department"].mode()[0])

In [42]:
df.isna().sum()

age           0
salary        0
department    0
dtype: int64

In [43]:
df

    age   salary department
0  20.0  30000.0         IT
1  22.0  45000.0         HR
2  25.0  45000.0         IT
3  30.0  60000.0         HR
4  28.0  45000.0         HR

In [44]:
df.groupby("department")["salary"].mean()

department
HR    50000.0
IT    37500.0
Name: salary, dtype: float64

In [45]:
df.groupby("department").agg({
    "age" : "mean",
    "salary" : ["mean", "median", "count"]
})

                  age   salary
                 mean     mean   median count
department
HR          26.666667  50000.0  45000.0     3
IT          22.500000  37500.0  37500.0     2

In [46]:
df.groupby("department").agg({
    "salary": "mean"
})

             salary
department
HR          50000.0
IT          37500.0

In [47]:
df.groupby("department")["salary"].mean().reset_index()

  department   salary
0         HR  50000.0
1         IT  37500.0

In [48]:
df

    age   salary department
0  20.0  30000.0         IT
1  22.0  45000.0         HR
2  25.0  45000.0         IT
3  30.0  60000.0         HR
4  28.0  45000.0         HR

In [49]:
df.groupby("department")["age"].mean()

department
HR    26.666667
IT    22.500000
Name: age, dtype: float64

In [50]:
df.groupby("department")["salary"].median()

department
HR    45000.0
IT    37500.0
Name: salary, dtype: float64

In [51]:
df.groupby("department").count().reset_index()

  department  age  salary
0         HR    3       3
1         IT    2       2

In [52]:
pd.get_dummies(df, columns=["department"])

    age   salary  department_HR  department_IT
0  20.0  30000.0          False           True
1  22.0  45000.0           True          False
2  25.0  45000.0          False           True
3  30.0  60000.0           True          False
4  28.0  45000.0           True          False

In [59]:
X = pd.get_dummies(df[["age", "department"]], drop_first=True)
print(X)

    age  department_IT
0  20.0           True
1  22.0          False
2  25.0           True
3  30.0          False
4  28.0          False

In [55]:
y = df["salary"]

In [57]:
X_np = X.values
y_np = y.values

[[20.0 True]
 [22.0 False]
 [25.0 True]
 [30.0 False]
 [28.0 False]]